version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: 'SEND4'
    ports:
      - '${TYPEORM_PORT}:5432'
    volumes:
      - ${VOLUME_PATH}
    restart: always
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
